# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/rosemary/setup-makefiles.sh

AB_OTA_PARTITIONS += \
    audio_dsp \
    cam_vpu1 \
    cam_vpu2 \
    cam_vpu3 \
    gz \
    lk \
    md1img \
    scp \
    spmfw \
    sspm \
    tee
